### ISSUE TITLE
Cannot store tree, contains unknown blob

### ISSUE THREAD

**Issue by brandon-leapyear** [commercialhaskell/pantry#27] opened 2020-09-21 23:23 UTC
Using `stack` built from `master` (downloaded from https://github.com/commercialhaskell/stack/actions/runs/265180359), we're now getting random failures that look like
```
Cannot store tree, contains unknown blob: 18d5d2248a51ab29a488c8ea8c3786b00f50db4fea52f61766beffe3426bb85a,1475
CallStack (from HasCallStack):
  error, called at src/Pantry/Storage.hs:716:24 in pantry-0.5.1.1-AAruwtvutyxBsFeECnCnpy:Pantry.Storage
```
Unfortunately, I can't find this error occur in any of the per-package logs, so I don't know which package caused this error.

I'm also noticing these messages:
```
$ grep 'Did not find' 0.txt
Did not find tree key in DB after pulling it from Casa: e4daa79eb6a4442ec85c86dfeb0eb4bf8624f8dcc5291a2216165120ecb77c13,210 (for fail-4.9.0.0@sha256:35d1ee29364447c1b7d616bb1ee31f162b73e85fea91d7ca6441cf901398f572,1051 (from Hackage))
Did not find tree key in DB after pulling it from Casa: 9d1b9732339d893bf03b2a8ca619430b4b601ee2c9c07f80188c2d54e23573cf,699 (for contravariant-1.5.2@sha256:853259271870000c007a281f0bf0bf6e1aaa97c5fd5cd5734d7b0d79b9de2af5,2761 (from Hackage))
Did not find tree key in DB after pulling it from Casa: cb14c77d6a2acbfb3ccbb3ec8ad8682cc95baebcf2c291fdb6aab5332a6a92ee,10736 (for base-compat-batteries-0.11.1@sha256:2763af26f6bd118dc278b805988acc792443f08bd77da03ac5c438c2b1ab4aab,8666 (from Hackage))
Did not find tree key in DB after pulling it from Casa: 750fe7796d62dd4258e6a94b94d42e6528e50084e7b68ce7dd31ea0d713591c3,371 (for monad-time-0.3.1.0@sha256:77fd2e1fa0d5103e0fc68cd9dde5e014c72eb034b9cf94adf85f7e457f23128d,1497 (from Hackage))
Did not find tree key in DB after pulling it from Casa: 807aa9f8278604645d08882c44b3615f69c9189096471edb5fab26f9ea28cf5f,551 (for network-uri-2.6.3.0@sha256:d2d9ff3a80d9b2d1ff317a354bc0c56cc109c69a4c2449e5fc712d3ddce83ede,2902 (from Hackage))
Did not find tree key in DB after pulling it from Casa: 5f3ba13587475816f6f43b5bc5c139382a734b48c638ae9a6183e3c7fa759343,264 (for network-bsd-2.8.1.0@sha256:d92423549794926f8bac0b63d5963c898a2ab628a4bb2e10ec5ce05b579383c1,3742 (from Hackage))
Did not find tree key in DB after pulling it from Casa: 890bbbdf4175a409efd7c7c9fe153b71680e33bebeb74c9351d7d9d3a59d3d0e,810 (for old-time-1.1.0.3@sha256:c91fbb3ee73d20ccd015842b30f1f29a304893ebe0ae3128b7bbc13d5bb0d4c8,1328 (from Hackage))
Did not find tree key in DB after pulling it from Casa: b917f922fc59d98d47b789f50c5a569d1b80ae08d52f4fbebbaad7fc62479e0d,2202 (for QuickCheck-2.13.2@sha256:636e7265bf75122e7e2f97627c47aad3b772ee3b35b134cafb6095116ce8d07a,6974 (from Hackage))
Did not find tree key in DB after pulling it from Casa: 159d286ceffeb01795ea7d844f1ee26f0e9e25b62ee26388177fdbe9c20bccf3,465 (for universe-base-1.1.1@sha256:2882b0f86c6f7155b0e597e238f17462feb3b017510519422447085836860118,2561 (from Hackage))
Did not find tree key in DB after pulling it from Casa: 0e4527c25b0c292a72db414b3f5f16598426f6d57f56a678fc4d746fba4f441f,3056 (for math-functions-0.3.4.0@sha256:05965e844d0d6a8aba3b8272778fe03ee9ae31beb907d10445c9b5a03ffbd9bf,4200 (from Hackage))  
```

**Comment by snoyberg** [comment] 2020-09-22 08:58
Thank you for the report, I can't reproduce but I think I know what's causing it. I've pushed a commit to hopefully address this. I've kicked off a PR on Stack so that we'll get some CI-generated binaries. I'll ping when ready, would you be able to test those and see if they fix the issue?

**Comment by snoyberg** [comment] 2020-09-22 10:43
The binaries are now available at https://ecstatic-lalande-e25bf2.netlify.app/

**Comment by snoyberg** [comment] 2020-09-22 11:03
Sorry for previous comment, it included the wrong link. Actual link for binaries https://github.com/commercialhaskell/stack/actions/runs/266593212

**Comment by brandon-leapyear** [comment] 2020-09-22 15:58
I actually don't need this patch anymore; the issue was Circle CI caching the `.stack-work` directories. After clearing the cache and building the `.stack-work` and `~/.stack` directories from scratch, I don't get the errors anymore.

I can try to test those binaries still, if you want

**Comment by brandon-leapyear** [comment] 2020-09-22 17:16
Never mind. Got the error on a second run. I'll try this version. We also got another error:
```
Not cryptographic hash found for Hackage package regex-base-0.94.0.0
```

**Comment by brandon-leapyear** [comment] 2020-09-22 18:09
Update: tried the new version, still got the error
```
Cannot store tree, contains unknown blob: c444ff17521b23b3b8a00f09239759ea31e68868defcf3837ee3877d415022fd,3140
CallStack (from HasCallStack):
  error, called at src/Pantry/Storage.hs:718:24 in pantry-0.5.1.3-HemONZn3ffDJIxPWvykhdS:Pantry.Storage

Exited with code exit status 1
CircleCI received exit code 1
```
```
Version 2.4.0, Git revision 18ccd3539ded64a5affc8049e6752b8a42b64582 PRE-RELEASE x86_64 hpack-0.33.0
```

**Comment by snoyberg** [comment] 2020-09-23 03:24
This is really helpful, thanks. For future tests, would you mind enabling `--verbose` to get a bit more information?

I've made a deeper refactoring on pantry to make that code path impossible (yay static types). Would you mind testing the new executables when they're complete? They're available at https://github.com/commercialhaskell/stack/actions/runs/268027755

**Comment by brandon-leapyear** [comment] 2020-09-23 21:57
It seems like the mac run failed?

**Comment by snoyberg** [comment] 2020-09-24 03:35
Transient failure, this workflow succeeded https://github.com/commercialhaskell/stack/actions/runs/269673393

**Comment by mpilgrem** [comment] 2023-05-16 19:28
I am going to close this issue, given the passage of time and it seems to have been addressed.

**Closed by mpilgrem** 2023-05-16 19:28 UTC
